### ISSUE TITLE
Can't connect witt Sophos router with OpenVPN v 21.

### ISSUE THREAD

**Issue by sajonCC** [OpenVPN/openvpn3-linux#261]
Dear All,

Due to some hardware issues (new laptop) I had to upgrade my installation to Fedora 40. After that I'm not able any more to connect with my company VPN saver which is provided by SOPHOS firewall.

A bit of the story. In the past I was not able to connect with company VPN while using the latest released of openvpn3 client (v21). I found that I can connect with version v20. I've compiled this version from the source and problem was solved. Right now after an upgrade to latest Fedora, I can't even compile v20 due to compatibility issues with glib2 library of that version.

My company is not going to change the firewall which will support connection from version v21. I'm still able to connect with my company VPN from Windows based machine with the latest client (v 3.4.3).

Can somebody is able to help me to understand how I can get version 21 of openvpn3 working with my company vpn?

This is an error message I'm receiving?

> Session path: /net/openvpn/v3/sessions/1043f54cse818s42d3sbc07sdc708d836fe8
> Auth User name: xxxxx
> Auth Password: 
> ** Aborted **
> ** ERROR ** Failed to disconnect tunnel (object does not exist)

**Comment by dsommers** [comment]
Can you please try to install the dev-snapshot build?

https://copr.fedorainfracloud.org/coprs/dsommers/openvpn3-devsnapshots/

**Comment by sajonCC** [comment]
Hi.

Thank you for your fast reaction.

I've installed devsnapshots, results are the same.
![OpenVpn3_development_snapshot_installation_process](https://github.com/OpenVPN/openvpn3-linux/assets/76811268/be0ac702-fb23-473e-8f67-c890b0c69da7)

trying to connect:
![OpenVPN_connection](https://github.com/OpenVPN/openvpn3-linux/assets/76811268/d24f3f1b-36b7-4f6d-8641-df66946357c9)

And this is a log

```Jun 05 12:20:45 fedora openvpn3-service-logger[2744]: {tag:11575778627062126844} Parsed single-use configuration 'CC-PROJECTS_sajon.ovpn', owner: sajon
Jun 05 12:20:45 fedora openvpn3-service-logger[2744]: {tag:11575778627062126844} Setting configuration override 'persist-tun' to 'true' by UID 1000
Jun 05 12:20:45 fedora systemd[1]: Started dbus-:1.3-net.openvpn.v3.backends@2.service.
Jun 05 12:20:45 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dbus-:1.3-net.openvpn.v3.backends@2 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 05 12:20:45 fedora openvpn3-service-backendstart[3945]: OpenVPN3/Linux git:HEAD:e7531f45d3743bfe (openvpn3-service-backendstart)
Jun 05 12:20:45 fedora openvpn3-service-backendstart[3945]: OpenVPN core 3.git:HEAD:7590cb10 linux x86_64 64-bit
Jun 05 12:20:45 fedora openvpn3-service-backendstart[3945]: Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
Jun 05 12:20:45 fedora openvpn3-service-logger[2744]: Attached: {tag:17992520706840604305}  [:1.148/net.openvpn.v3.backends]
Jun 05 12:20:45 fedora openvpn3-service-backendstart[3950]: Re-initiated process from pid 3950 to backend process pid 3951
Jun 05 12:20:45 fedora openvpn3-service-backendstart[3951]: OpenVPN3/Linux git:HEAD:e7531f45d3743bfe (openvpn3-service-client)
Jun 05 12:20:45 fedora openvpn3-service-backendstart[3951]: OpenVPN core 3.git:HEAD:7590cb10 linux x86_64 64-bit
Jun 05 12:20:45 fedora openvpn3-service-backendstart[3951]: Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
Jun 05 12:20:45 fedora openvpn3-service-logger[2744]: Attached: {tag:1656527326253231390}  [:1.149/net.openvpn.v3.backends]
Jun 05 12:20:45 fedora openvpn3-service-logger[2744]: Attached: {tag:9914235973840458002}  [:1.149/net.openvpn.v3.sessions]
Jun 05 12:20:45 fedora openvpn3-service-logger[2744]: Assigned session /net/openvpn/v3/sessions/e948e404see5cs4727s8d1as322c8e8d0938 to {tag:1656527326253231390}
Jun 05 12:20:45 fedora audit: BPF prog-id=113 op=LOAD
Jun 05 12:20:45 fedora audit: BPF prog-id=114 op=LOAD
Jun 05 12:20:45 fedora audit: BPF prog-id=115 op=LOAD
Jun 05 12:20:45 fedora systemd[1]: Starting systemd-hostnamed.service - Hostname Service...
Jun 05 12:20:45 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 05 12:20:45 fedora systemd[1]: Started systemd-hostnamed.service - Hostname Service.
Jun 05 12:20:48 fedora openvpn3-service-logger[2744]: Detached: {tag:17992520706840604305}  [:1.148/net.openvpn.v3.backends]
Jun 05 12:20:48 fedora systemd[1]: dbus-:1.3-net.openvpn.v3.backends@2.service: Deactivated successfully.
Jun 05 12:20:48 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dbus-:1.3-net.openvpn.v3.backends@2 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 05 12:20:48 fedora systemd[1]: dbus-:1.3-net.openvpn.v3.backends@2.service: Unit process 3951 (openvpn3-servic) remains running after unit stopped.
Jun 05 12:20:51 fedora audit[3951]: ANOM_ABEND auid=4294967295 uid=993 gid=991 ses=4294967295 subj=system_u:system_r:openvpn3_client_t:s0 pid=3951 comm="openvpn3-servic" exe="/usr/libexec/openvpn3-linux/openvpn3-service-client" sig=11 res=1
Jun 05 12:20:51 fedora kernel: openvpn3-servic[3951]: segfault at 7fb6bb143282 ip 00007fb152b6a491 sp 00007fffb75e6d38 error 4 in libgobject-2.0.so.0.8000.2[7fb152b3c000+37000] likely on CPU 1 (core 1, socket 0)
Jun 05 12:20:51 fedora kernel: Code: 00 00 00 4c 89 ce e9 ae e6 ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 f3 0f 1e fa 48 85 ff 74 47 48 8b 07 48 85 c0 74 3f <48> 8b 00 48 3d fc 03 00 00 77 2c 48 8d 15 7d 3c 02 00 48 c1 e8 02
Jun 05 12:20:51 fedora audit: BPF prog-id=116 op=LOAD
Jun 05 12:20:51 fedora audit: BPF prog-id=117 op=LOAD
Jun 05 12:20:51 fedora audit: BPF prog-id=118 op=LOAD
Jun 05 12:20:51 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-3958-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 05 12:20:51 fedora audit: BPF prog-id=119 op=LOAD
Jun 05 12:20:51 fedora systemd[1]: Started systemd-coredump@2-3958-0.service - Process Core Dump (PID 3958/UID 0).
Jun 05 12:20:51 fedora audit: BPF prog-id=120 op=LOAD
Jun 05 12:20:51 fedora audit: BPF prog-id=121 op=LOAD
Jun 05 12:20:51 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=drkonqi-coredump-processor@2-3958-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 05 12:20:51 fedora systemd[1]: Started drkonqi-coredump-processor@2-3958-0.service - Pass systemd-coredump journal entries to relevant user for potential DrKonqi handling.
Jun 05 12:20:51 fedora systemd-coredump[3959]: [🡕] Process 3951 (openvpn3-servic) of user 993 dumped core.

                                               Module libblkid.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                                               Module libzstd.so.1 from rpm zstd-1.5.6-1.fc40.x86_64
                                               Module liblzma.so.5 from rpm xz-5.4.6-3.fc40.x86_64
                                               Module libcap.so.2 from rpm libcap-2.69-8.fc40.x86_64
                                               Module libpcre2-8.so.0 from rpm pcre2-10.42-2.fc40.2.x86_64
                                               Module libffi.so.8 from rpm libffi-3.4.4-7.fc40.x86_64
                                               Module libmount.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                                               Module libgmodule-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libz.so.1 from rpm zlib-ng-2.1.6-2.fc40.x86_64
                                               Module libselinux.so.1 from rpm libselinux-3.6-4.fc40.x86_64
                                               Module libsystemd.so.0 from rpm systemd-255.6-1.fc40.x86_64
                                               Module libuuid.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                                               Module liblz4.so.1 from rpm lz4-1.9.4-6.fc40.x86_64
                                               Module libjsoncpp.so.25 from rpm jsoncpp-1.9.5-7.fc40.x86_64
                                               Module libglib-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libgobject-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libgio-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libcrypto.so.3 from rpm openssl-3.2.1-2.fc40.x86_64
                                               Module libssl.so.3 from rpm openssl-3.2.1-2.fc40.x86_64
                                               Stack trace of thread 3951:
                                               #0  0x00007fb152b6a491 g_type_check_instance_is_fundamentally_a (libgobject-2.0.so.0 + 0x39491)
                                               #1  0x00007fb152b5172f g_object_unref (libgobject-2.0.so.0 + 0x2072f)
                                               #2  0x00007fb1523389b5 g_source_callback_unref (libglib-2.0.so.0 + 0x539b5)
                                               #3  0x00007fb15233fbec g_source_destroy_internal (libglib-2.0.so.0 + 0x5abec)
                                               #4  0x00007fb1523417c9 g_main_context_dispatch_unlocked.lto_priv.0 (libglib-2.0.so.0 + 0x5c7c9)
                                               #5  0x00007fb1523a2708 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbd708)
                                               #6  0x00007fb152347667 g_main_loop_run (libglib-2.0.so.0 + 0x62667)
                                               #7  0x00000000004232f6 _Z19start_client_threadiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES4_bibP9LogWriter (openvpn3-service-client + 0x232f6)
                                               #8  0x000000000042693f _Z14client_serviceSt10shared_ptrI10ParsedArgsE (openvpn3-service-client + 0x2693f)
                                               #9  0x00000000004e100f _ZN13SingleCommand10RunCommandENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjiPPc (openvpn3-service-client + 0xe100f)
                                               #10 0x000000000041a7da _ZN13SingleCommand10RunCommandENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiPPc (openvpn3-service-client + 0x1a7da)
                                               #11 0x00007fb151c3d088 __libc_start_call_main (libc.so.6 + 0x2a088)
                                               #12 0x00007fb151c3d14b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
                                               #13 0x000000000041e5c5 _start (openvpn3-service-client + 0x1e5c5)

                                               Stack trace of thread 3952:
                                               #0  0x00007fb151d2918d syscall (libc.so.6 + 0x11618d)
                                               #1  0x00007fb15239f7bd g_cond_wait (libglib-2.0.so.0 + 0xba7bd)
                                               #2  0x00007fb15230c5ab g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x275ab)
                                               #3  0x00007fb152372a53 g_thread_pool_spawn_thread (libglib-2.0.so.0 + 0x8da53)
                                               #4  0x00007fb152371863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #5  0x00007fb151ca91b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007fb151d2b39c __clone3 (libc.so.6 + 0x11839c)

                                               Stack trace of thread 3954:
                                               #0  0x00007fb151d1d72d __poll (libc.so.6 + 0x10a72d)
                                               #1  0x00007fb1523a26a4 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbd6a4)
                                               #2  0x00007fb152347667 g_main_loop_run (libglib-2.0.so.0 + 0x62667)
                                               #3  0x00007fb152546e82 gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x114e82)
                                               #4  0x00007fb152371863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #5  0x00007fb151ca91b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007fb151d2b39c __clone3 (libc.so.6 + 0x11839c)

                                               Stack trace of thread 3953:
                                               #0  0x00007fb151d1d72d __poll (libc.so.6 + 0x10a72d)
                                               #1  0x00007fb1523a26a4 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbd6a4)
                                               #2  0x00007fb152342b23 g_main_context_iteration (libglib-2.0.so.0 + 0x5db23)
                                               #3  0x00007fb152342b79 glib_worker_main (libglib-2.0.so.0 + 0x5db79)
                                               #4  0x00007fb152371863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #5  0x00007fb151ca91b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007fb151d2b39c __clone3 (libc.so.6 + 0x11839c)
                                               ELF object binary architecture: AMD x86-64
Jun 05 12:20:51 fedora systemd[1]: systemd-coredump@2-3958-0.service: Deactivated successfully.
Jun 05 12:20:51 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-3958-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 05 12:20:51 fedora audit: BPF prog-id=118 op=UNLOAD
Jun 05 12:20:51 fedora audit: BPF prog-id=117 op=UNLOAD
Jun 05 12:20:51 fedora audit: BPF prog-id=116 op=UNLOAD
Jun 05 12:20:51 fedora drkonqi-coredump-processor[3960]: The socket path doesn't exist @ "/run/user/993/drkonqi-coredump-launcher"
Jun 05 12:20:51 fedora systemd[1]: drkonqi-coredump-processor@2-3958-0.service: Deactivated successfully.
Jun 05 12:20:51 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=drkonqi-coredump-processor@2-3958-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 05 12:20:51 fedora audit: BPF prog-id=121 op=UNLOAD
Jun 05 12:20:51 fedora audit: BPF prog-id=120 op=UNLOAD
Jun 05 12:20:51 fedora audit: BPF prog-id=119 op=UNLOAD
Jun 05 12:20:51 fedora abrt-server[3973]: Executable '/usr/libexec/openvpn3-linux/openvpn3-service-client' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Jun 05 12:20:51 fedora abrt-server[3973]: 'post-create' on '/var/spool/abrt/ccpp-2024-06-05-12:20:51.422566-3951' exited with 1
Jun 05 12:20:51 fedora abrt-server[3973]: Deleting problem directory '/var/spool/abrt/ccpp-2024-06-05-12:20:51.422566-3951'
Jun 05 12:21:04 fedora openvpn3-service-logger[2744]: {tag:9393428089721246559} Session is  closing

**Comment by dsommers** [comment]
I just pushed out an updated devsnapshot, I know there has been some code changes which may be related to your issue.  Especially if your OpenVPN server side uses an older approach for OTP authentication.

It could also help if you can install the `debuginfo` packages as well, that way the coredump splat should give even better indications on where in the source code it fails.  IIRC, `dnf debuginfo-install openvpn3 openvpn3-client` will do the trick.

**Comment by sajonCC** [comment]
I've installed as per your request. It's still not working. Although it throw a different error message.

![image](https://github.com/OpenVPN/openvpn3-linux/assets/76811268/c9a04f52-5cf7-45ba-b0ec-3b4f54e08942)

This is a log dump

```Jun 06 07:50:31 fedora openvpn3-service-log[2858]: {tag:4350873103455095077} Parsed single-use configuration 'CC-PROJECTS_sajon.ovpn, owner: sajon
Jun 06 07:50:31 fedora openvpn3-service-log[2858]: {tag:4350873103455095077} Setting configuration override 'persist-tun' to 'true' by UID 1000
Jun 06 07:50:31 fedora systemd[1]: Created slice system-dbus\x2d:1.3\x2dnet.openvpn.v3.backends.slice - Slice /system/dbus-:1.3-net.openvpn.v3.backends.
Jun 06 07:50:31 fedora systemd[1]: Started dbus-:1.3-net.openvpn.v3.backends@0.service.
Jun 06 07:50:31 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dbus-:1.3-net.openvpn.v3.backends@0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 07:50:31 fedora openvpn3-service-backendstart[2881]: OpenVPN3/Linux git:HEAD:e7531f45d3743bfe (openvpn3-service-backendstart)
Jun 06 07:50:31 fedora openvpn3-service-backendstart[2881]: OpenVPN core 3.git:HEAD:7590cb10 linux x86_64 64-bit
Jun 06 07:50:31 fedora openvpn3-service-backendstart[2881]: Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
Jun 06 07:50:31 fedora openvpn3-service-backendstart[2887]: Re-initiated process from pid 2887 to backend process pid 2888
Jun 06 07:50:31 fedora openvpn3-service-backendstart[2888]: OpenVPN3/Linux git:HEAD:e7531f45d3743bfe (openvpn3-service-client)
Jun 06 07:50:31 fedora openvpn3-service-backendstart[2888]: OpenVPN core 3.git:HEAD:7590cb10 linux x86_64 64-bit
Jun 06 07:50:31 fedora openvpn3-service-backendstart[2888]: Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
Jun 06 07:50:31 fedora audit: BPF prog-id=91 op=LOAD
Jun 06 07:50:31 fedora audit: BPF prog-id=92 op=LOAD
Jun 06 07:50:31 fedora audit: BPF prog-id=93 op=LOAD
Jun 06 07:50:31 fedora systemd[1]: Starting systemd-hostnamed.service - Hostname Service...
Jun 06 07:50:31 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 07:50:31 fedora systemd[1]: Started systemd-hostnamed.service - Hostname Service.
Jun 06 07:50:31 fedora systemd[1]: Created slice system-dbus\x2d:1.3\x2dnet.openvpn.v3.netcfg.slice - Slice /system/dbus-:1.3-net.openvpn.v3.netcfg.
Jun 06 07:50:31 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dbus-:1.3-net.openvpn.v3.netcfg@0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 07:50:31 fedora systemd[1]: Started dbus-:1.3-net.openvpn.v3.netcfg@0.service.
Jun 06 07:50:31 fedora openvpn3-service-netcfg[2893]: Loading configuration file: /var/lib/openvpn3/netcfg.json
Jun 06 07:50:31 fedora openvpn3-service-netcfg[2893]: openvpn3-linux master:4f37952340f0e5d3 (openvpn3-service-netcfg)
Jun 06 07:50:31 fedora openvpn3-service-netcfg[2893]: OpenVPN core 3.git:release_3.8.5:03236ed7 linux x86_64 64-bit
Jun 06 07:50:31 fedora openvpn3-service-netcfg[2893]: Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
Jun 06 07:50:34 fedora kernel: show_signal_msg: 54 callbacks suppressed
Jun 06 07:50:34 fedora kernel: openvpn3-servic[2888]: segfault at 7f2062794362 ip 00007f27a4aed491 sp 00007ffc9452dbc8 error 4 in libgobject-2.0.so.0.8000.2[7f27a4abf000+37000] likely on CPU 0 (core 0, socket 0)
Jun 06 07:50:34 fedora kernel: Code: 00 00 00 4c 89 ce e9 ae e6 ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 f3 0f 1e fa 48 85 ff 74 47 48 8b 07 48 85 c0 74 3f <48> 8b 00 48 3d fc 03 00 00 77 2c 48 8d 15 7d 3c 02 00 48 c1 e8 02
Jun 06 07:50:34 fedora audit[2888]: ANOM_ABEND auid=4294967295 uid=993 gid=991 ses=4294967295 subj=system_u:system_r:openvpn3_client_t:s0 pid=2888 comm="openvpn3-servic" exe="/usr/libexec/openvpn3-linux/openvpn3-service-client" sig=11 res=1
Jun 06 07:50:34 fedora systemd[1]: Created slice system-drkonqi\x2dcoredump\x2dprocessor.slice - Slice /system/drkonqi-coredump-processor.
Jun 06 07:50:34 fedora systemd[1]: Created slice system-systemd\x2dcoredump.slice - Slice /system/systemd-coredump.
Jun 06 07:50:34 fedora audit: BPF prog-id=94 op=LOAD
Jun 06 07:50:34 fedora audit: BPF prog-id=95 op=LOAD
Jun 06 07:50:34 fedora audit: BPF prog-id=96 op=LOAD
Jun 06 07:50:34 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@0-2898-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 07:50:34 fedora systemd[1]: Started systemd-coredump@0-2898-0.service - Process Core Dump (PID 2898/UID 0).
Jun 06 07:50:34 fedora audit: BPF prog-id=97 op=LOAD
Jun 06 07:50:34 fedora audit: BPF prog-id=98 op=LOAD
Jun 06 07:50:34 fedora audit: BPF prog-id=99 op=LOAD
Jun 06 07:50:34 fedora systemd[1]: Started drkonqi-coredump-processor@0-2898-0.service - Pass systemd-coredump journal entries to relevant user for potential DrKonqi handling.
Jun 06 07:50:34 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=drkonqi-coredump-processor@0-2898-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 07:50:34 fedora systemd-coredump[2899]: [🡕] Process 2888 (openvpn3-servic) of user 993 dumped core.

                                               Module libblkid.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                                               Module libzstd.so.1 from rpm zstd-1.5.6-1.fc40.x86_64
                                               Module liblzma.so.5 from rpm xz-5.4.6-3.fc40.x86_64
                                               Module libcap.so.2 from rpm libcap-2.69-8.fc40.x86_64
                                               Module libpcre2-8.so.0 from rpm pcre2-10.42-2.fc40.2.x86_64
                                               Module libffi.so.8 from rpm libffi-3.4.4-7.fc40.x86_64
                                               Module libmount.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                                               Module libgmodule-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libz.so.1 from rpm zlib-ng-2.1.6-2.fc40.x86_64
                                               Module libselinux.so.1 from rpm libselinux-3.6-4.fc40.x86_64
                                               Module libsystemd.so.0 from rpm systemd-255.7-1.fc40.x86_64
                                               Module libuuid.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                                               Module liblz4.so.1 from rpm lz4-1.9.4-6.fc40.x86_64
                                               Module libjsoncpp.so.25 from rpm jsoncpp-1.9.5-7.fc40.x86_64
                                               Module libglib-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libgobject-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libgio-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libcrypto.so.3 from rpm openssl-3.2.1-2.fc40.x86_64
                                               Module libssl.so.3 from rpm openssl-3.2.1-2.fc40.x86_64
                                               Stack trace of thread 2888:
                                               #0  0x00007f27a4aed491 g_type_check_instance_is_fundamentally_a (libgobject-2.0.so.0 + 0x39491)
                                               #1  0x00007f27a4ad472f g_object_unref (libgobject-2.0.so.0 + 0x2072f)
                                               #2  0x00007f27a43389b5 g_source_callback_unref (libglib-2.0.so.0 + 0x539b5)
                                               #3  0x00007f27a433fbec g_source_destroy_internal (libglib-2.0.so.0 + 0x5abec)
                                               #4  0x00007f27a43417c9 g_main_context_dispatch_unlocked.lto_priv.0 (libglib-2.0.so.0 + 0x5c7c9)
                                               #5  0x00007f27a43a2708 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbd708)
                                               #6  0x00007f27a4347667 g_main_loop_run (libglib-2.0.so.0 + 0x62667)
                                               #7  0x00000000004232f6 _Z19start_client_threadiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES4_bibP9LogWriter (openvpn3-service-client + 0x232f6)
                                               #8  0x000000000042693f _Z14client_serviceSt10shared_ptrI10ParsedArgsE (openvpn3-service-client + 0x2693f)
                                               #9  0x00000000004e100f _ZN13SingleCommand10RunCommandENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjiPPc (openvpn3-service-client + 0xe100f)
                                               #10 0x000000000041a7da _ZN13SingleCommand10RunCommandENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiPPc (openvpn3-service-client + 0x1a7da)
                                               #11 0x00007f27a3c10088 __libc_start_call_main (libc.so.6 + 0x2a088)
                                               #12 0x00007f27a3c1014b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
                                               #13 0x000000000041e5c5 _start (openvpn3-service-client + 0x1e5c5)

                                               Stack trace of thread 2890:
                                               #0  0x00007f27a3cf072d __poll (libc.so.6 + 0x10a72d)
                                               #1  0x00007f27a43a26a4 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbd6a4)
                                               #2  0x00007f27a4342b23 g_main_context_iteration (libglib-2.0.so.0 + 0x5db23)
                                               #3  0x00007f27a4342b79 glib_worker_main (libglib-2.0.so.0 + 0x5db79)
                                               #4  0x00007f27a4371863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #5  0x00007f27a3c7c1b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007f27a3cfe39c __clone3 (libc.so.6 + 0x11839c)

                                               Stack trace of thread 2891:
                                               #0  0x00007f27a3cf072d __poll (libc.so.6 + 0x10a72d)
                                               #1  0x00007f27a43a26a4 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbd6a4)
                                               #2  0x00007f27a4347667 g_main_loop_run (libglib-2.0.so.0 + 0x62667)
                                               #3  0x00007f27a4546e82 gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x114e82)
                                               #4  0x00007f27a4371863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #5  0x00007f27a3c7c1b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007f27a3cfe39c __clone3 (libc.so.6 + 0x11839c)

                                               Stack trace of thread 2889:
                                               #0  0x00007f27a3cfc18d syscall (libc.so.6 + 0x11618d)
                                               #1  0x00007f27a439f7bd g_cond_wait (libglib-2.0.so.0 + 0xba7bd)
                                               #2  0x00007f27a430c5ab g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x275ab)
                                               #3  0x00007f27a4372a53 g_thread_pool_spawn_thread (libglib-2.0.so.0 + 0x8da53)
                                               #4  0x00007f27a4371863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #5  0x00007f27a3c7c1b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007f27a3cfe39c __clone3 (libc.so.6 + 0x11839c)
                                               ELF object binary architecture: AMD x86-64
Jun 06 07:50:34 fedora systemd[1]: systemd-coredump@0-2898-0.service: Deactivated successfully.
Jun 06 07:50:34 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@0-2898-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 07:50:34 fedora audit: BPF prog-id=96 op=UNLOAD
Jun 06 07:50:34 fedora audit: BPF prog-id=95 op=UNLOAD
Jun 06 07:50:34 fedora audit: BPF prog-id=94 op=UNLOAD
Jun 06 07:50:34 fedora drkonqi-coredump-processor[2900]: The socket path doesn't exist @ "/run/user/993/drkonqi-coredump-launcher"
Jun 06 07:50:34 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=drkonqi-coredump-processor@0-2898-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 07:50:34 fedora systemd[1]: drkonqi-coredump-processor@0-2898-0.service: Deactivated successfully.
Jun 06 07:50:34 fedora audit: BPF prog-id=99 op=UNLOAD
Jun 06 07:50:34 fedora audit: BPF prog-id=98 op=UNLOAD
Jun 06 07:50:34 fedora audit: BPF prog-id=97 op=UNLOAD
Jun 06 07:50:34 fedora abrt-server[2911]: Executable '/usr/libexec/openvpn3-linux/openvpn3-service-client' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Jun 06 07:50:34 fedora abrt-server[2911]: 'post-create' on '/var/spool/abrt/ccpp-2024-06-06-07:50:34.626005-2888' exited with 1
Jun 06 07:50:34 fedora abrt-server[2911]: Deleting problem directory '/var/spool/abrt/ccpp-2024-06-06-07:50:34.626005-2888'
Jun 06 07:50:37 fedora openvpn3-service-log[2858]: {tag:16157968296814443238} Shutting down
Jun 06 07:50:37 fedora systemd[1]: dbus-:1.3-net.openvpn.v3.backends@0.service: Deactivated successfully.
Jun 06 07:50:37 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dbus-:1.3-net.openvpn.v3.backends@0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 07:50:37 fedora openvpn3-service-log[2858]: Could not find an attach subscription for [:1.105/net.openvpn.v3.backends], pid 2881, caller :1.105

**Comment by dsommers** [comment]
I've been trying to understand what's happening, but the information in the coredump is just lacking enough details to fully understand where it halts so far.  I've uploaded a simple tool I put together today, which generates a sanitised configuration profile (please double check the output does not provide any sensitive info) ... can you please run that on your configuration and provide the output?  Maybe that will give a better hint on why this fails so quicly.

https://gist.github.com/dsommers/36f8439c874ee15be8a929fa0dc63e5f/raw/4189c96821e66d8753de593f11954e25d7ac3054/support-profile-exporter.py

How to use it:
```
$ curl https://gist.github.com/dsommers/36f8439c874ee15be8a929fa0dc63e5f/raw/4189c96821e66d8753de593f11954e25d7ac3054/support-profile-exporter.py > setup-profile.exporter
$ chmod 755 setup-profile.exporter
$ ./setup-profile.exporter --config-file CONFIG_FILE
# or ....
$  ./setup-profile.exporter --config-profile CONFIG_PROFILE_NAME
```

The second one is used if you have imported the configuration profile using `openvpn3 config-import`.  The first one will parse the configuration file you have on disk.

**Comment by sajonCC** [comment]
curl command to download your script is not working. I ended up with empty file. I do not know why. When I open the link in the browser and copy the content of the file. When running the script, I've received a lot of errors from python. I'm sorry, I'm not a programmed and at this moment I do not have time to look in to it with details (sorry for that). Below is the output of the command.

```xxxx@fedora:~/Documents/VPN_TEST$ ./setup-profile.exporter --config-file xxx.ovpn 
Traceback (most recent call last):
  File "/home/sxxxx/Documents/VPN_TEST/./setup-profile.exporter", line 116, in <module>
    ovpncfg = parse_config_file(opts.config_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/Documents/VPN_TEST/./setup-profile.exporter", line 52, in parse_config_file
    cfg = SanitiseConfig(fname)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/Documents/VPN_TEST/./setup-profile.exporter", line 18, in __init__
    super().__init__(['SantiseConfig', '--config', fname], 'SanitiseConfig')
  File "/usr/lib/python3.12/site-packages/openvpn3/ConfigParser.py", line 79, in __init__
    self.__opts = vars(self.__parser.parse_args(self.__args))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/argparse.py", line 1896, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/argparse.py", line 1929, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/argparse.py", line 2150, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/argparse.py", line 2090, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.12/argparse.py", line 2005, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.12/site-packages/openvpn3/ConfigParser.py", line 988, in __call__
    args = vars(parser.parse_args(shlex.split('\n'.join(cfg),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/argparse.py", line 1899, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python3.12/site-packages/openvpn3/ConfigParser.py", line 54, in error
    raise Exception("%s: error: %s"  % (self.prog, message))
Exception: SantiseConfig: error: unrecognized arguments: -- -- -- -- --route-delay 4 --verb 3 --reneg-sec 0 --remote xxx.xxx.xxx.xxx 8443 tcp-client --remote xxx.xxx.xxx.xxx 8443 tcp-client --remote 10.31.211.1 8443 tcp-client --remote 10.31.212.1 8443 tcp-client --remote 10.31.213.1 8443 tcp-client --remote 10.31.214.1 8443 tcp-client --remote 10.31.219.1 8443 tcp-client --remote 10.31.220.1 8443 tcp-client

**Comment by dsommers** [comment]
Okay, thanks a lot!  Could you then try to just provide a sanitised config, without certificates, keys and host names removed from `remote` lines?

Alternatively, try to import your config file using `openvpn3 config-import` and run the script using `--config-profile PROFILE-NAME` ...
```
$ openvpn3 config-import --name debug-config --config /path/to/config.ovpn
$ ./setup-profile.exporter --config-profile debug-config
```

**Comment by sajonCC** [comment]
Hi,

Sanitised config file attached

[VPN.zip](https://github.com/user-attachments/files/15640330/VPN.zip)

This is a result:
```auth SHA256
<auth-user-pass>
# INLINE DATA REMOVED
</auth-user-pass>
<ca>
# INLINE DATA REMOVED
</ca>
<cert>
# INLINE DATA REMOVED
</cert>
cipher AES-128-CBC
comp-lzo yes
dev tun
<key>
# INLINE DATA REMOVED
</key>
proto tcp
remote remote.host.removed 8443 tcp-client
remote remote.host.removed 8443 tcp-client
remote remote.host.removed 8443 tcp-client
remote remote.host.removed 8443 tcp-client
remote remote.host.removed 8443 tcp-client
remote remote.host.removed 8443 tcp-client
remote remote.host.removed 8443 tcp-client
remote remote.host.removed 8443 tcp-client
reneg-sec 0
resolv-retry infinite
route ['remote_host', '255.255.255.255', 'net_gateway']
route-delay 4
verb 3
verify-x509-name C=NL, ST=NH, L=, O=, OU=OU, CN=SophosApplianceCertificate_C1A0A43HCD7C991, emailAddress=

**Comment by dsommers** [comment]
thanks! that blob is exactly what I was hoping to see ... But I'm not able to reproduce it .... However I spotted a detail in your logs now:

     Jun 06 07:50:31 fedora openvpn3-service-backendstart[2888]: OpenVPN3/Linux git:HEAD:e7531f45d3743bfe (openvpn3-service-client)

That version string is not correct if you are running the latest development snapshot .... I would expect to see this string:

     openvpn3-linux master:4f37952340f0e5d3 (openvpn3-service-client)

Can you please verify you have enabled the `dsommers/openvpn3-devsnapshots` Copr repo and upgraded properly?

     # dnf copr enable dsommers/openvpn3-devsnapshots
     # dnf remove openvpn3-client openvpn3
     # dnf install openvpn3-client openvpn3

The `e7531f45d3743bfe` reference points at the `v20` release, which is known to have issues since Fedora 38.

**Comment by sajonCC** [comment]
OK, followed the steps to installed correct version. It's still not working, here is a log:

```Jun 06 18:07:18 fedora openvpn3-service-log[2858]: {tag:430283044873178068} Parsed single-use configuration 'CC-PROJECTS_sajon.ovpn, owner: sajon
Jun 06 18:07:18 fedora openvpn3-service-log[2858]: {tag:430283044873178068} Setting configuration override 'persist-tun' to 'true' by UID 1000
Jun 06 18:07:18 fedora openvpn3-service-backendstart[5484]: Re-initiated process from pid 5484 to backend process pid 5485
Jun 06 18:07:18 fedora openvpn3-service-backendstart[5485]: openvpn3-linux master:4f37952340f0e5d3 (openvpn3-service-client)
Jun 06 18:07:18 fedora openvpn3-service-backendstart[5485]: OpenVPN core 3.git:release_3.8.5:03236ed7 linux x86_64 64-bit
Jun 06 18:07:18 fedora openvpn3-service-backendstart[5485]: Copyright (C) 2012-2022 OpenVPN Inc. All rights reserved.
Jun 06 18:07:18 fedora audit: BPF prog-id=140 op=LOAD
Jun 06 18:07:18 fedora audit: BPF prog-id=141 op=LOAD
Jun 06 18:07:18 fedora audit: BPF prog-id=142 op=LOAD
Jun 06 18:07:18 fedora systemd[1]: Starting systemd-hostnamed.service - Hostname Service...
Jun 06 18:07:18 fedora systemd[1]: Started systemd-hostnamed.service - Hostname Service.
Jun 06 18:07:18 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 18:07:28 fedora openvpn3-service-log[2858]: {tag:10287183416664571881} Cleaning up resources for PID 5485.
Jun 06 18:07:28 fedora openvpn3-service-log[2858]: {tag:2775509633603611724} Starting connection
Jun 06 18:07:28 fedora openvpn3-service-log[2858]: {tag:10287183416664571881} Socket protect called for socket 8, remote: '77.61.186.235', tun: '', ipv6: no, device_path=/, device-object: missing
Jun 06 18:07:29 fedora openvpn3-service-log[2858]: {tag:2775509633603611724} Connecting
Jun 06 18:07:31 fedora openvpn3-service-log[2858]: {tag:10287183416664571881} Virtual device '8a722993te52ct49fat90d5t106f9ab1c164' registered on /net/openvpn/v3/netcfg/5485_8a722993te52ct49fat90d5t106f9ab1c164 (owner uid 993, owner pid 5485)
Jun 06 18:07:31 fedora openvpn3-service-log[2858]: {tag:10287183416664571881} Adding IP Address 10.81.234.3/24 gw 10.81.234.1 ipv6: no
Jun 06 18:07:31 fedora openvpn3-service-log[2858]: {tag:10287183416664571881} Setting remote IP address to 77.61.186.235 ipv6: no
Jun 06 18:07:31 fedora openvpn3-service-log[2858]: {tag:10287183416664571881} Adding network '10.31.212.0/24' excl: no ipv6: no
Jun 06 18:07:31 fedora openvpn3-service-log[2858]: {tag:10287183416664571881} Adding network '10.31.211.0/24' excl: no ipv6: no
Jun 06 18:07:31 fedora NetworkManager[1102]: <info>  [1717690051.5967] manager: (tun0): new Tun device (/org/freedesktop/NetworkManager/Devices/4)
Jun 06 18:07:31 fedora openvpn3-service-log[2858]: {tag:2775509633603611724} Connected: sajon@77.61.186.235:8443 (77.61.186.235) via /TCP on tun/10.81.234.3/ gw=[10.81.234.1/] mtu=(default)
Jun 06 18:07:31 fedora openvpn3-service-log[2858]: {tag:2775509633603611724} [COMPRESS_ERROR] server pushed compression settings that are not allowed and will result in a non-working connection.
Jun 06 18:07:31 fedora openvpn3-service-log[2858]: {tag:2775509633603611724} Disconnected
Jun 06 18:07:31 fedora openvpn3-service-netcfg[5409]: Error while executing NetlinkAddr4(add: 0) tun0: -19
Jun 06 18:07:31 fedora openvpn3-service-netcfg[5409]: Error while executing NetlinkLinkSet tun0 mtu 1500: -1
Jun 06 18:07:31 fedora openvpn3-service-netcfg[5409]: Error while executing NetlinkLinkSet tun0 up 0: -2
Jun 06 18:07:32 fedora openvpn3-service-log[2858]: {tag:10287183416664571881} Cleaning up resources for PID 5485.
Jun 06 18:07:32 fedora audit[5485]: ANOM_ABEND auid=4294967295 uid=993 gid=991 ses=4294967295 subj=system_u:system_r:openvpn3_client_t:s0 pid=5485 comm="pool" exe="/usr/libexec/openvpn3-linux/openvpn3-service-client" sig=11 res=1
Jun 06 18:07:32 fedora kernel: pool[5490]: segfault at 18 ip 0000557c58d848f3 sp 00007f4ce25ff9e0 error 4 in openvpn3-service-client[557c58ccd000+11b000] likely on CPU 1 (core 1, socket 0)
Jun 06 18:07:32 fedora kernel: Code: e8 a2 c6 04 00 48 8b 7d 98 4c 39 ff 74 0d 48 8b 45 a8 48 8d 70 01 e8 2c ab f4 ff 4c 89 e7 e8 94 04 01 00 48 8b 85 30 ff ff ff <48> 8b 40 18 0f b6 80 99 04 00 00 84 c0 0f 85 da 00 00 00 48 8b bb
Jun 06 18:07:32 fedora openvpn3-service-log[2858]: {tag:2775509633603611724} Stopping connection
Jun 06 18:07:32 fedora audit: BPF prog-id=143 op=LOAD
Jun 06 18:07:32 fedora audit: BPF prog-id=144 op=LOAD
Jun 06 18:07:32 fedora audit: BPF prog-id=145 op=LOAD
Jun 06 18:07:32 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-5511-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 18:07:32 fedora systemd[1]: Started systemd-coredump@2-5511-0.service - Process Core Dump (PID 5511/UID 0).
Jun 06 18:07:32 fedora audit: BPF prog-id=146 op=LOAD
Jun 06 18:07:32 fedora audit: BPF prog-id=147 op=LOAD
Jun 06 18:07:32 fedora audit: BPF prog-id=148 op=LOAD
Jun 06 18:07:32 fedora systemd[1]: Started drkonqi-coredump-processor@2-5511-0.service - Pass systemd-coredump journal entries to relevant user for potential DrKonqi handling.
Jun 06 18:07:32 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=drkonqi-coredump-processor@2-5511-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 18:07:32 fedora systemd-coredump[5512]: [🡕] Process 5485 (openvpn3-servic) of user 993 dumped core.

                                               Module libblkid.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                                               Module libffi.so.8 from rpm libffi-3.4.4-7.fc40.x86_64
                                               Module libselinux.so.1 from rpm libselinux-3.6-4.fc40.x86_64
                                               Module libmount.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                                               Module libgmodule-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libz.so.1 from rpm zlib-ng-2.1.6-2.fc40.x86_64
                                               Module libpcre2-8.so.0 from rpm pcre2-10.42-2.fc40.2.x86_64
                                               Module libgobject-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libgio-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libzstd.so.1 from rpm zstd-1.5.6-1.fc40.x86_64
                                               Module liblzma.so.5 from rpm xz-5.4.6-3.fc40.x86_64
                                               Module libcap.so.2 from rpm libcap-2.69-8.fc40.x86_64
                                               Module libprotobuf.so.30 from rpm protobuf-3.19.6-8.fc40.x86_64
                                               Module libnl-genl-3.so.200 from rpm libnl3-3.9.0-3.fc40.x86_64
                                               Module libuuid.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                                               Module libcrypto.so.3 from rpm openssl-3.2.1-2.fc40.x86_64
                                               Module libssl.so.3 from rpm openssl-3.2.1-2.fc40.x86_64
                                               Module libnl-3.so.200 from rpm libnl3-3.9.0-3.fc40.x86_64
                                               Module libglib-2.0.so.0 from rpm glib2-2.80.2-1.fc40.x86_64
                                               Module libgdbuspp.so.1 from rpm gdbuspp-0.20240605git7d80f553d64ec647-1.fc40.x86_64
                                               Module libsystemd.so.0 from rpm systemd-255.7-1.fc40.x86_64
                                               Module liblz4.so.1 from rpm lz4-1.9.4-6.fc40.x86_64
                                               Module libjsoncpp.so.25 from rpm jsoncpp-1.9.5-7.fc40.x86_64
                                               Module openvpn3-service-client from rpm openvpn3-21-4.gdbusdev7.fc40.x86_64
                                               Stack trace of thread 5490:
                                               #0  0x0000557c58d848f3 _ZNKSt13__atomic_baseIbE4loadESt12memory_order (openvpn3-service-client + 0xc98f3)
                                               #1  0x0000557c58da7b98 _ZNSt17_Function_handlerIFvSt10shared_ptrIN4DBus6Object6Method9ArgumentsEEEZN19BackendClientObjectC4ES0_INS1_10ConnectionEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS2_4PathESF_jP9LogWriterbEUlS5_E6_E9_M_invokeERKSt9_Any_dataOS5_ (openvpn3-service-client + 0xecb98)
                                               #2  0x00007f4ce59c5dd7 _ZN4DBus6Object6Method8Callback7ExecuteERSt10unique_ptrINS_12AsyncProcess7RequestESt14default_deleteIS5_EE (libgdbuspp.so.1 + 0x2ddd7)
                                               #3  0x00007f4ce59bc73c _ZN5glib29Callbacks24_int_pool_processpool_cbEPvS1_ (libgdbuspp.so.1 + 0x2473c)
                                               #4  0x00007f4ce58d9582 g_thread_pool_thread_proxy.lto_priv.0 (libglib-2.0.so.0 + 0x8e582)
                                               #5  0x00007f4ce58d7863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #6  0x00007f4ce48a91b7 start_thread (libc.so.6 + 0x961b7)
                                               #7  0x00007f4ce492b39c __clone3 (libc.so.6 + 0x11839c)

                                               Stack trace of thread 5505:
                                               #0  0x00007f4ce48f45e3 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xe15e3)
                                               #1  0x00007f4ce4900387 __nanosleep (libc.so.6 + 0xed387)
                                               #2  0x00007f4ce4912301 sleep (libc.so.6 + 0xff301)
                                               #3  0x0000557c58dbc012 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN14BackendSignals8LogFATALERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEUlvE_EEEEE6_M_runEv (openvpn3-service-client + 0x101012)
                                               #4  0x00007f4ce4ae6524 execute_native_thread_routine (libstdc++.so.6 + 0xe6524)
                                               #5  0x00007f4ce48a91b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007f4ce492b39c __clone3 (libc.so.6 + 0x11839c)

                                               Stack trace of thread 5487:
                                               #0  0x00007f4ce491d72d __poll (libc.so.6 + 0x10a72d)
                                               #1  0x00007f4ce59086a4 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbd6a4)
                                               #2  0x00007f4ce58a8b23 g_main_context_iteration (libglib-2.0.so.0 + 0x5db23)
                                               #3  0x00007f4ce58a8b79 glib_worker_main (libglib-2.0.so.0 + 0x5db79)
                                               #4  0x00007f4ce58d7863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #5  0x00007f4ce48a91b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007f4ce492b39c __clone3 (libc.so.6 + 0x11839c)

                                               Stack trace of thread 5485:
                                               #0  0x00007f4ce491d72d __poll (libc.so.6 + 0x10a72d)
                                               #1  0x00007f4ce59086a4 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbd6a4)
                                               #2  0x00007f4ce58ad667 g_main_loop_run (libglib-2.0.so.0 + 0x62667)
                                               #3  0x00007f4ce59b91ea _ZN4DBus8MainLoop3RunEv (libgdbuspp.so.1 + 0x211ea)
                                               #4  0x0000557c58d93a4f _Z19start_client_threadiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES4_biP9LogWriter (openvpn3-service-client + 0xd8a4f)
                                               #5  0x0000557c58dced7e _ZN13SingleCommand10RunCommandERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjiPPc (openvpn3-service-client + 0x113d7e)
                                               #6  0x0000557c58d07683 _ZN13SingleCommand10RunCommandERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiPPc (openvpn3-service-client + 0x4c683)
                                               #7  0x00007f4ce483d088 __libc_start_call_main (libc.so.6 + 0x2a088)
                                               #8  0x00007f4ce483d14b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
                                               #9  0x0000557c58d0f605 _start (openvpn3-service-client + 0x54605)

                                               Stack trace of thread 5488:
                                               #0  0x00007f4ce491d72d __poll (libc.so.6 + 0x10a72d)
                                               #1  0x00007f4ce59086a4 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbd6a4)
                                               #2  0x00007f4ce58ad667 g_main_loop_run (libglib-2.0.so.0 + 0x62667)
                                               #3  0x00007f4ce4759e82 gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x114e82)
                                               #4  0x00007f4ce58d7863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #5  0x00007f4ce48a91b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007f4ce492b39c __clone3 (libc.so.6 + 0x11839c)

                                               Stack trace of thread 5486:
                                               #0  0x00007f4ce492918d syscall (libc.so.6 + 0x11618d)
                                               #1  0x00007f4ce59057bd g_cond_wait (libglib-2.0.so.0 + 0xba7bd)
                                               #2  0x00007f4ce58725ab g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x275ab)
                                               #3  0x00007f4ce58d8a53 g_thread_pool_spawn_thread (libglib-2.0.so.0 + 0x8da53)
                                               #4  0x00007f4ce58d7863 g_thread_proxy (libglib-2.0.so.0 + 0x8c863)
                                               #5  0x00007f4ce48a91b7 start_thread (libc.so.6 + 0x961b7)
                                               #6  0x00007f4ce492b39c __clone3 (libc.so.6 + 0x11839c)
                                               ELF object binary architecture: AMD x86-64
Jun 06 18:07:32 fedora systemd[1]: systemd-coredump@2-5511-0.service: Deactivated successfully.
Jun 06 18:07:32 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-5511-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 18:07:32 fedora audit: BPF prog-id=145 op=UNLOAD
Jun 06 18:07:32 fedora audit: BPF prog-id=144 op=UNLOAD
Jun 06 18:07:32 fedora audit: BPF prog-id=143 op=UNLOAD
Jun 06 18:07:32 fedora drkonqi-coredump-processor[5513]: The socket path doesn't exist @ "/run/user/993/drkonqi-coredump-launcher"
Jun 06 18:07:32 fedora systemd[1]: drkonqi-coredump-processor@2-5511-0.service: Deactivated successfully.
Jun 06 18:07:32 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=drkonqi-coredump-processor@2-5511-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 06 18:07:32 fedora audit: BPF prog-id=148 op=UNLOAD
Jun 06 18:07:32 fedora audit: BPF prog-id=147 op=UNLOAD
Jun 06 18:07:32 fedora audit: BPF prog-id=146 op=UNLOAD
Jun 06 18:07:32 fedora abrt-server[5524]: Package 'openvpn3-client' isn't signed with proper key
Jun 06 18:07:32 fedora abrt-server[5524]: 'post-create' on '/var/spool/abrt/ccpp-2024-06-06-18:07:32.629131-5485' exited with 1
Jun 06 18:07:32 fedora abrt-server[5524]: Deleting problem directory '/var/spool/abrt/ccpp-2024-06-06-18:07:32.629131-5485'

**Comment by dsommers** [comment]
Now we have a real reason it fails ... There's a crash which should not happen, but that's more a consequence of this error, I'd say

     [COMPRESS_ERROR] server pushed compression settings that are not allowed and will result in a non-working connection.

You will now need to use the import method and explicitly allow compression to be allowed to connect.  Compression has been deprecated for many years, so it might be that the Sophos installation is getting quite old and missing some updates.

     $ openvpn3 config-import --persistent --config /path/to/config.ovpn --name CONFIG_NAME
     $ openvpn3 config-manage --show --config CONFIG_NAME --allow-compression yes

To start the configuration, you use almost the same command:

     $ openvpn3 session-start --config CONFIG_NAME

Starting/stopping sessions will now also work with both the [openvpn3-indicator](https://github.com/OpenVPN/openvpn3-indicator/) and `systemctl {start,stop} openvpn3-session@CONFIG_NAME.service`

**Comment by sajonCC** [comment]
Thanks, it works in Fedora 40.

Do you know how to install openvpn3 in opensuse?

**Comment by dsommers** [comment]
Currently we don't provide any builds for SUSE at all.  But if you retrieve the source RPMs, you will probably the most important pieces to get started.  But it most likely will need a little bit of fiddling with the `gdbuspp.spec` and `openvpn3.spec` to get the dependencies correct.  SUSE names library and development packages slightly different from Fedora/RHEL.

      $ dnf download --source openvpn3 gdbuspp

Otherwise, it's needed to build from source ...
* GDBus++ - https://codeberg.org/OpenVPN/gdbuspp/#how-to-build
* OpenVPN 3 Linux - https://codeberg.org/OpenVPN/openvpn3-linux/src/branch/master/BUILD.md#fedora-and-red-hat-enterprise-linux

**Comment by dsommers** [comment]
Since this issue is now resolved (it is possible to establish a connection), I'll close it now.  This code provided in this development snapshot will be part of the coming `v22_dev` release.
